name: Checks
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
jobs:
  installation_and_download:
    name: Installation
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[SKIP-CI]')"
    steps:
      - uses: actions/checkout@v1
      - name: 'Install Google drive upload'
        run: |
          bash install.sh
              eval "$(< "${HOME}/.google-drive-upload/google-drive-upload.binpath")"
              gupload --help
          sudo bash install.sh -B master -c custom_gupload -p /usr/bin
              eval "$(< "${HOME}/.google-drive-upload/google-drive-upload.binpath")"
              custom_gupload --help
